<a href="https://colab.research.google.com/github/esranoyan/Ders-Notebooklari/blob/main/Numpy_1_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin.

In [ ]:
arr = np.array([[[1,2], [4,5]], [[7,8], [9,10]]])  #Veri sayısı farklı olursa 'VisibleDeprecationWarning' hatası veriyor
arr


array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [ 9, 10]]])

In [ ]:
arr.ndim

3

2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.

In [ ]:
arr = np.arange(34,113,6)
arr

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [ ]:
arr.ndim

1


3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)

In [ ]:
np.linspace(50,500,91, dtype=int)

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

4) 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.

In [ ]:
log_arr = np.logspace(2,5,8)
log_arr

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.

In [ ]:
arr= np.diag([0,1,2,3,4,5,6,7,8]) ,  #3x3 shape inde olmadı

matrix= np.array([[0,1,2] , [3,4,5], [6,7,8]])
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
matrix.shape

(3, 3)

In [ ]:
 new_try= np.arange(0,9).reshape(3,3) #üstteki ile aynı sonucu verdi.
 new_try

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)

In [ ]:
arr1= np.zeros((6,6) , dtype=int)
arr1  

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
arr1.shape

(6, 6)

 7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)

In [ ]:
arr= np.ones((4,4) , dtype=int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
arr.shape

(4, 4)

8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

In [ ]:
arr= np.diag([1,0,0,0,0,0,0,0])
arr

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.shape

(8, 8)

9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)

In [ ]:
arr= np.diag([3,3,3,3,3])
arr

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

In [ ]:
arr= np.random.rand(6)
arr

array([0.93299228, 0.83258695, 0.15311392, 0.33994331, 0.91586439,
       0.77708837])

In [ ]:
arr.ndim

1

11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

In [ ]:
arr1= np.random.randint(50,101 , (5,2))
arr1

array([[63, 77],
       [60, 88],
       [60, 87],
       [55, 57],
       [80, 93]])

In [ ]:
arr1.shape

(5, 2)

12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

In [ ]:
arr= np.random.randint(low=100, high=1000, size=(2,5,5))
arr

array([[[672, 250, 422, 242, 690],
        [460, 411, 507, 856, 714],
        [566, 936, 688, 243, 340],
        [750, 279, 874, 577, 588],
        [986, 547, 295, 390, 255]],

       [[431, 916, 471, 298, 221],
        [668, 865, 584, 506, 543],
        [971, 127, 650, 527, 986],
        [666, 345, 891, 993, 969],
        [946, 198, 313, 725, 619]]])

In [ ]:
arr.shape

(2, 5, 5)

In [ ]:
arr.ndim

3

13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

In [ ]:
arr= np.random.randint(0,101,10)
arr

array([29, 53, 46, 48,  3,  2, 36, 33, 49, 30])

In [ ]:
arr.max()

53

In [ ]:
arr.argmax()

1

In [ ]:
arr.min()

2

In [ ]:
arr.argmin()

5

14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

In [ ]:
arr= np.random.randint(300,501, (2,2,5))
arr

array([[[453, 429, 301, 481, 427],
        [307, 493, 384, 352, 391]],

       [[403, 389, 415, 401, 486],
        [300, 348, 380, 335, 339]]])

In [ ]:
arr_min = arr[1][1][0]
arr_min

300

In [ ]:
arr_max = arr[0][1][1]
arr_max

493

15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [ ]:
arr= np.arange(0,51)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
arr[20:36] = 500
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])