<a href="https://colab.research.google.com/github/esranoyan/Ders-Notebooklari/blob/main/Numpy_2_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.

In [ ]:
arr1d = np.arange(0,30, dtype=int)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr1d.ndim

1

In [ ]:
arr2d = arr1d.reshape(15,2)
arr2d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [ ]:
arr2d.ndim

2

In [ ]:
arr2d.shape

(15, 2)

2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [ ]:
arr1d = np.random.rand(60) * 20
arr1d

array([ 7.28803954, 16.58005278,  8.63642172,  8.00660373,  0.95797655,
        1.58407012,  2.89429197,  4.40116194,  3.98302475, 15.90309907,
       17.86472539,  8.94879648,  7.88519089,  9.64963225, 10.87114122,
        0.16175572, 16.31206413, 17.31908253,  4.37657013, 18.11667708,
       18.44769585,  5.41333956,  1.70855564, 17.63238243,  2.15740953,
        6.64803753,  8.44848267, 15.85820047,  2.79007642, 17.12398111,
       16.98376376,  8.39203225, 18.07204222,  6.49468953,  9.29444635,
       17.38143984, 16.34121626,  3.02524363, 16.33131161,  8.51811898,
       18.36231422, 14.76077826, 10.74767021, 17.16383992, 17.43699331,
       10.59623402, 18.95127009, 16.32487052,  5.61196933,  4.17447422,
        4.18906857, 15.50783602, 14.23717058, 18.98440765,  5.7358897 ,
        1.95428505,  5.55847572, 19.18512085, 16.86733387, 16.35668024])

In [ ]:
array = arr1d.reshape(5,-1,2)
array

array([[[ 7.28803954, 16.58005278],
        [ 8.63642172,  8.00660373],
        [ 0.95797655,  1.58407012],
        [ 2.89429197,  4.40116194],
        [ 3.98302475, 15.90309907],
        [17.86472539,  8.94879648]],

       [[ 7.88519089,  9.64963225],
        [10.87114122,  0.16175572],
        [16.31206413, 17.31908253],
        [ 4.37657013, 18.11667708],
        [18.44769585,  5.41333956],
        [ 1.70855564, 17.63238243]],

       [[ 2.15740953,  6.64803753],
        [ 8.44848267, 15.85820047],
        [ 2.79007642, 17.12398111],
        [16.98376376,  8.39203225],
        [18.07204222,  6.49468953],
        [ 9.29444635, 17.38143984]],

       [[16.34121626,  3.02524363],
        [16.33131161,  8.51811898],
        [18.36231422, 14.76077826],
        [10.74767021, 17.16383992],
        [17.43699331, 10.59623402],
        [18.95127009, 16.32487052]],

       [[ 5.61196933,  4.17447422],
        [ 4.18906857, 15.50783602],
        [14.23717058, 18.98440765],
        [ 5.7358897 

In [ ]:
array.shape

(5, 6, 2)

In [ ]:
array.ndim

3

3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [ ]:
arr = np.linspace(0,50,20).reshape(5,-1,2)
arr

array([[[ 0.        ,  2.63157895],
        [ 5.26315789,  7.89473684]],

       [[10.52631579, 13.15789474],
        [15.78947368, 18.42105263]],

       [[21.05263158, 23.68421053],
        [26.31578947, 28.94736842]],

       [[31.57894737, 34.21052632],
        [36.84210526, 39.47368421]],

       [[42.10526316, 44.73684211],
        [47.36842105, 50.        ]]])

In [ ]:
arr1d = arr.reshape(-1)
arr1d

array([34, 15, 12, 15, 30, 25, 32, 31, 34,  6, 19, 33, 39, 49, 23, 13, 45,
       18, 24, 15])

In [ ]:
arr1d.ndim

1

In [ ]:
arr1d.shape

(20,)

4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.

In [ ]:
arr = np.arange(0,30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
for i in arr:
  for x in i:
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [ ]:
for x in np.nditer(arr):
  print(x)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.

In [ ]:
arr1 = np.arange(5,31,5)
arr1

array([ 5, 10, 15, 20, 25, 30])

In [ ]:
arr2 = np.arange(1,7)
arr2

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1[1] + arr2[1]

12

In [ ]:
arr1[1] - arr2[1]

8

In [ ]:
arr1[1] * arr2[1]

20

In [ ]:
arr1[1] / arr2[1]

5.0

6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.

In [ ]:
arrx = np.random.randint(0,100,10)
arrx

array([30, 18, 99, 76, 29, 35, 88,  4, 93, 74])

In [ ]:
arrx.sum()

546

In [ ]:
arrx.mean()

54.6

In [ ]:
arrx.max()

99

In [ ]:
arrx.var()

1094.04

In [ ]:
arrx.std()

33.07627548561053

7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.

In [ ]:
arr1 = np.arange(0,20)
arr2 = np.arange(500,531)

In [ ]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr2

array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530])

In [ ]:
np.concatenate([arr1,arr2])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.

In [ ]:
arr1 = np.arange(15,51)
arr2 = np.arange(10,101)
arr3 = np.concatenate([arr1,arr2])
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
arr3[25:50] = 888
arr3 

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.

In [ ]:
arr1 = np.arange(0,40).reshape(8,5)
arr2 = np.arange(320,360).reshape(8,5)

In [ ]:
np.concatenate([arr1,arr2], axis=0) 

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [ ]:
np.concatenate([arr1,arr2], axis=1)

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.

In [ ]:
np.concatenate([arr1,arr2], axis=2) # 2 boyutlu array için axisi 2 yapamadı.

AxisError: ignored

In [ ]:
np.stack([arr1,arr2], axis=2) # Yeni bir boyut üzerinde yığınlama yaptı.

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.

In [ ]:
arr = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
arr

array([ 1, 20, 25,  4,  4,  5,  4,  4,  1,  6,  9, 12,  1,  5])

In [ ]:
np.where(arr==5)

(array([ 5, 13]),)

12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.

In [ ]:
np.where(arr%2 ==0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.

In [ ]:
np.where(arr>4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.

In [ ]:
np.where(arr%5 ==0)

(array([ 1,  2,  5, 13]),)

15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin

In [ ]:
np.random.randint(85,101, dtype=int)

100

16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.

In [ ]:
arr= np.random.randint(10,100, (3,3))
arr

array([[74, 23, 37],
       [13, 70, 31],
       [87, 41, 96]])

In [ ]:
arr.shape

(3, 3)

17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.

In [ ]:
arr= np.arange(35,60)
arr

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
np.random.choice(arr)

57

18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.


In [ ]:
arr= np.array([10,8,3,3,8,53,8,10,53,3])
arr

array([10,  8,  3,  3,  8, 53,  8, 10, 53,  3])

In [ ]:
arr.reshape(2,5)

array([[10,  8,  3,  3,  8],
       [53,  8, 10, 53,  3]])